[project]
name = "example-robot-data"
version = "4.0.3.2"
description = "Set of robot URDFs for benchmarking and developed examples."
readme = "README.md"
license= "BSD-3-Clause"
dependencies = ["pin"]

[project.urls]
homepage = "https://github.com/gepetto/example-robot-data"

[tool.cmeel]
build-number = 1
run-tests-after-install = true

[tool.isort]
line_length = 88

[build-system]
build-backend = "cmeel.build"
requires = ["cmeel[build]", "pin", "cmeel-eigen", "cmeel-urdfdom-headers", "cmeel-tinyxml"]
